steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/job-url-extractor', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/job-url-extractor'

options:
  logging: CLOUD_LOGGING_ONLY
